apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  NODE_ENV: production
  PORT: "3000"
  LOG_LEVEL: info
  APP_NAME: nodejs-eks-app
  REGION: us-east-1
