apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
type: Opaque
stringData:
  DB_USER: admin
  DB_PASSWORD: admin123
  JWT_SECRET: myjwtsecret
  API_KEY: super-api-key
  EMAIL_PASSWORD: emailpass123
  REDIS_PASS: redispass
